# Corne Cherry v4 with nice_view
---
include:
  - board: nice_nano//zmk
    shield: corne_cherry_v4_left nice_view_adapter nice_view
  - board: nice_nano//zmk
    shield: corne_cherry_v4_right nice_view_adapter nice_view
  - board: nice_nano//zmk
    shield: settings_reset
